micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/cdcdb`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:cdc}
    password: ${DB_PASSWORD:cdc}

jpa.default.properties.hibernate.hbm2ddl.auto: update
